AddOnInitializePropManagerFunction(function()
	modimport("upe/palette_icons")
	ModImportOnAllThreads("upe/property_list_duplicator")
	ModImportOnAllThreads("upe/property_list_postinit")
	ModImportOnAllThreads("upe/property_replacer")
end)