AddOnInitializePropManagerFunction(function()
	require("upe/palette_icons")
	RequireOnAllThreads("upe/property_list_duplicator")
	RequireOnAllThreads("upe/property_list_postinit")
	RequireOnAllThreads("upe/property_replacer")
end)